"""Del profiles

Revision ID: 63315e0fd25f
Revises: 419a671383e3
Create Date: 2024-11-15 14:41:30.259648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63315e0fd25f"
down_revision: Union[str, None] = "419a671383e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("username", sa.String(), nullable=False))
    op.add_column("Users", sa.Column("email", sa.String(), nullable=False))
    op.drop_constraint("Users_profile_id_fkey", "Users", type_="foreignkey")
    op.drop_column("Users", "profile_id")
    # ### end Alembic commands ###
    op.drop_table("Profiles")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users",
        sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "Users_profile_id_fkey", "Users", "Profiles", ["profile_id"], ["id"]
    )
    op.drop_column("Users", "email")
    op.drop_column("Users", "username")
    op.create_table(
        "Profiles",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
