"""add column count in OrderProduct

Revision ID: 1d5f8302ceaa
Revises: 4b536592aac6
Create Date: 2024-11-02 18:29:49.985340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d5f8302ceaa"
down_revision: Union[str, None] = "4b536592aac6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "OrderProduct",
        sa.Column("count", sa.Integer(), server_default="1", nullable=True),
    )
    op.alter_column("Orders", "promo", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Orders", "promo", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("OrderProduct", "count")
    # ### end Alembic commands ###
