"""Del column in user

Revision ID: b5eff444553e
Revises: 1d631cd406d7
Create Date: 2024-10-12 14:12:14.572250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5eff444553e"
down_revision: Union[str, None] = "1d631cd406d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "sname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("sname", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
