"""add Resumes

Revision ID: 837d98accbc4
Revises: 1ff5d8d8109b
Create Date: 2024-10-25 12:17:14.879686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837d98accbc4'
down_revision: Union[str, None] = '1ff5d8d8109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resumes',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Enum('fulltime', 'partime', name='workload'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['Workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resumes')
    # ### end Alembic commands ###
