"""create refresh list

Revision ID: a9d988fc38b6
Revises: d30a00bb6fe7
Create Date: 2024-12-21 19:56:47.597073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d988fc38b6'
down_revision: Union[str, None] = 'd30a00bb6fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RefreshBlackList',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_id', sa.Integer(), nullable=False),
    sa.Column('expire', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RefreshList',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RefreshList')
    op.drop_table('RefreshBlackList')
    # ### end Alembic commands ###
