# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1egoogle/protobuf/wrappers.proto\"\\\n\x10\x43heckAuthRequest\x12\x37\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x88\x01\x01\x42\x0f\n\r_access_token\"M\n\x12RequestCredentials\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\xf2\x01\n\x11\x43heckAuthResponse\x12\x13\n\x0b\x61uth_status\x18\x01 \x01(\x08\x12;\n\x10new_access_token\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x88\x01\x01\x12\x1d\n\x10token_is_updated\x18\x03 \x01(\x08H\x01\x88\x01\x01\x12\x32\n\x0b\x63redentials\x18\x04 \x01(\x0b\x32\x18.auth.RequestCredentialsH\x02\x88\x01\x01\x42\x13\n\x11_new_access_tokenB\x13\n\x11_token_is_updatedB\x0e\n\x0c_credentials\"4\n\x0cLoginRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"`\n\rLoginResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x19\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_access_token\"H\n\rLogoutRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"5\n\x0eLogoutResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"-\n\x15GetCredentialsRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"Q\n\x16GetCredentialsResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t2\xff\x01\n\x0b\x41uthService\x12<\n\tCheckAuth\x12\x16.auth.CheckAuthRequest\x1a\x17.auth.CheckAuthResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.LogoutResponse\x12K\n\x0eGetCredentials\x12\x1b.auth.GetCredentialsRequest\x1a\x1c.auth.GetCredentialsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKAUTHREQUEST']._serialized_start=52
  _globals['_CHECKAUTHREQUEST']._serialized_end=144
  _globals['_REQUESTCREDENTIALS']._serialized_start=146
  _globals['_REQUESTCREDENTIALS']._serialized_end=223
  _globals['_CHECKAUTHRESPONSE']._serialized_start=226
  _globals['_CHECKAUTHRESPONSE']._serialized_end=468
  _globals['_LOGINREQUEST']._serialized_start=470
  _globals['_LOGINREQUEST']._serialized_end=522
  _globals['_LOGINRESPONSE']._serialized_start=524
  _globals['_LOGINRESPONSE']._serialized_end=620
  _globals['_LOGOUTREQUEST']._serialized_start=622
  _globals['_LOGOUTREQUEST']._serialized_end=694
  _globals['_LOGOUTRESPONSE']._serialized_start=696
  _globals['_LOGOUTRESPONSE']._serialized_end=749
  _globals['_GETCREDENTIALSREQUEST']._serialized_start=751
  _globals['_GETCREDENTIALSREQUEST']._serialized_end=796
  _globals['_GETCREDENTIALSRESPONSE']._serialized_start=798
  _globals['_GETCREDENTIALSRESPONSE']._serialized_end=879
  _globals['_AUTHSERVICE']._serialized_start=882
  _globals['_AUTHSERVICE']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
